---
title: "R Notebook"
output:
  html_notebook: 
    toc: yes
    theme: yeti
  pdf_document: default
---

## Estudio Clima

```{r}

renv::activate() # activa el entorno virtual
install.packages("tidyverse") # paquete tidyverse
```

```{r}
library(readr)
df <- read_delim("staticfiles/Excel_ClimaLV2.csv", 
    delim = ";", escape_double = FALSE, col_types = cols(Year = col_integer(), 
        AssociatedDis = col_character(), 
        DisMagValue = col_integer(), StartData = col_date(format = "%d/%m/%Y"), 
        EndData = col_date(format = "%d/%m/%Y"), 
        TotalDeaths = col_integer(), NoInjured = col_integer(), 
        NoAffected = col_integer(), NoHomeless = col_integer(), 
        TotalAffected = col_integer(), TotalDamages = col_double()), 
    trim_ws = TRUE)
```

```{r}
dim(df)
summary(df)
df
```



```{r}
install.packages("RSQLite")
library(RSQLite)
library(DBI)
```


```{r}
conn <- dbConnect(RSQLite::SQLite(), "db.sqlite3") #crea la conexion
dbCreateTable(conn, "desastres", df) # crea una tabla
dbListTables(conn) # lista las tablas

remove(desastres)

```


```{r}
data("desastres")
desastres <- rownames(df)
head(desastres)
```

```{r}
dbDisconnect(conn)
```
