# Generated by Django 4.0.3 on 2022-03-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('seq', models.CharField(max_length=100)),
                ('glide', models.CharField(max_length=100)),
                ('disastergroup', models.CharField(max_length=100)),
                ('disastersubgroup', models.CharField(max_length=100)),
                ('disastertype', models.CharField(max_length=100)),
                ('disastersubtype', models.CharField(max_length=100)),
                ('disastersubsubtype', models.CharField(max_length=100)),
                ('eventname', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('iso', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('continent', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('associateddis', models.CharField(max_length=100)),
                ('associateddis2', models.CharField(max_length=100)),
                ('ofdaresponse', models.CharField(max_length=100)),
                ('appeal', models.CharField(max_length=100)),
                ('declaration', models.CharField(max_length=100)),
                ('aidcontribution', models.CharField(max_length=100)),
                ('dismagvalue', models.CharField(max_length=100)),
                ('dismagscale', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('localtime', models.CharField(max_length=100)),
                ('riverbasin', models.CharField(max_length=100)),
                ('startyear', models.CharField(max_length=100)),
                ('startmonth', models.CharField(max_length=100)),
                ('startday', models.CharField(max_length=100)),
                ('endyear', models.CharField(max_length=100)),
                ('endmonth', models.CharField(max_length=100)),
                ('endday', models.CharField(max_length=100)),
                ('totaldeaths', models.CharField(max_length=100)),
                ('noinjured', models.CharField(max_length=100)),
                ('noaffected', models.CharField(max_length=100)),
                ('nohomeless', models.CharField(max_length=100)),
                ('totalaffected', models.CharField(max_length=100)),
                ('insureddamages000us', models.CharField(max_length=100)),
                ('totaldamages000us', models.CharField(max_length=100)),
                ('cpi', models.CharField(max_length=100)),
                ('admlevel', models.CharField(max_length=100)),
                ('admin1code', models.CharField(max_length=100)),
                ('admin2code', models.CharField(max_length=100)),
                ('geolocations', models.CharField(max_length=100)),
            ],
        ),
    ]
