# Generated by Django 4.0.3 on 2022-03-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='associated_dis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='continent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='dis_mag_scale',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='dis_mag_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='disaster_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='disaster_subgroup',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='disaster_subtype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='disaster_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='end_data',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='event_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='glide',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='iso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='no_affected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='no_homeless',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='no_injured',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='seq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='start_data',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='total_affected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='total_damages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='total_deaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
